# Generated by Django 3.2.5 on 2024-06-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_busshift_busstop'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='shift',
        ),
        migrations.DeleteModel(
            name='BusShift',
        ),
        migrations.DeleteModel(
            name='BusStop',
        ),
    ]
